"""Generate data/fingerprint_execution_matrix.json and docs/UPGRADE_V6_IMPLEMENTATION_AUDIT.md.

Maps every registered research method (the single source of truth, `app/research/methods.py`) to its taxonomy
family, representation, capability flags and honest status. Nothing is marked "ready" merely for appearing in a
dropdown: readiness comes from the registry's `availability == READY` and the `_CAP_FLAGS` capability table, which the
test-suite already validates.

    python scripts/build_execution_matrix.py
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from app import __version__  # noqa: E402
from app.research.methods import CAPABILITY_FLAGS, MethodRegistry  # noqa: E402

# category -> one of the seven taxonomy families kept distinct by the ontology
FAMILY_BY_CATEGORY = {
    "BASELINE": "BASELINE",
    "METADATA / PROVENANCE": "PROVENANCE",
    "INTRINSIC FINGERPRINT RESEARCH": "INTRINSIC",
    "DIFFUSION FORENSICS": "RECONSTRUCTION",
    "SPECTRAL": "SPECTRAL",
    "GEOMETRIC / STATISTICAL": "SPECTRAL",
    "SPATIAL / MULTI-SCALE": "INTRINSIC",
    "REPRESENTATION": "DETECTOR REPRESENTATION",
    "CAUSAL": "CAUSAL",
    "CONTROLLED SURROGATE STUDY": "PROACTIVE WATERMARK",
    "ADVANCED HYPOTHESIS": "INTRINSIC",
    "ENSEMBLE": "INTRINSIC",
    "RECONSTRUCTION FORENSICS": "RECONSTRUCTION",
    "FRONTIER": "INTRINSIC",
}
_TAX = re.compile(r"taxonomy\s+((?:\d[A-Z]?)(?:/\d[A-Z]?)*)", re.IGNORECASE)


def classification(flags: dict) -> list[str]:
    out = []
    if flags["CAN_ANALYZE"]:
        out.append("ANALYSIS")
    if flags["CAN_ESTIMATE"]:
        out.append("ESTIMATION")
    if flags["CAN_SEPARATE"]:
        out.append("SEPARATION")
    if flags["CAN_RECONSTRUCT"]:
        out.append("RECONSTRUCTION")
    if flags["CAN_VALIDATE"]:
        out.append("VALIDATION")
    return out or ["NONE (not runnable)"]


def build() -> dict:
    reg = MethodRegistry()
    rows = []
    for m in reg.all():
        flags = m.capability_flags()
        codes = _TAX.search(m.source_reference or "")
        rows.append({
            "method_id": m.method_id, "code": m.code, "name": m.name, "category": m.category,
            "fingerprint_family": FAMILY_BY_CATEGORY.get(m.category, "INTRINSIC"),
            "representation": m.subfamily, "maturity": m.maturity, "availability": m.availability,
            "taxonomy_codes": codes.group(1).split("/") if codes else [],
            "source_reference": m.source_reference, "license": m.license, "local_or_online": m.local_or_online,
            "requires_model": m.requires_model, "requires_gpu": m.requires_gpu,
            "requires_ground_truth": m.requires_ground_truth,
            "requires_reference_images": m.requires_reference_images,
            "capabilities": {k: flags[k] for k in CAPABILITY_FLAGS},
            "classification": classification(flags),
            "analyzer": m.capability if flags["CAN_ANALYZE"] else None,
            "estimator": m.capability if flags["CAN_ESTIMATE"] else None,
            "separator": m.capability if flags["CAN_SEPARATE"] else None,
            "reconstructor": m.capability if flags["CAN_RECONSTRUCT"] else None,
            "validator": m.capability if flags["CAN_VALIDATE"] else None,
            "reason_if_unavailable": m.reason or "",
            "runnable": m.runnable,
        })
    families: dict[str, list] = {}
    for r in rows:
        families.setdefault(r["fingerprint_family"], []).append(r["method_id"])
    return {"schema_version": "1.0", "software_version": __version__, "n_methods": len(rows),
            "families": {k: sorted(v) for k, v in sorted(families.items())},
            "note": "Mapping of taxonomy families to executable research stages with capability flags. Readiness is "
                    "from the method registry, not from UI presence. SEPARATION/RECONSTRUCTION are advertised only "
                    "where the capability actually provides them; detector-evasion methods stay NOT_IMPLEMENTED.",
            "methods": rows}


def audit_markdown(matrix: dict) -> str:
    rows = matrix["methods"]
    ready = [r for r in rows if r["runnable"]]
    out = [f"# Upgrade v6 — Implementation Audit", "",
           f"Generated by `scripts/build_execution_matrix.py` for SynthProvenance {matrix['software_version']}. "
           "It classifies every registered research method by capability. A method is **not** called ready for "
           "appearing in a dropdown: readiness is `availability == READY` plus the capability table in "
           "`app/research/methods.py`, which the test-suite validates (`test_registry_capabilities_are_honest`).", "",
           f"- **Methods total:** {len(rows)}",
           f"- **Runnable locally now (READY):** {len(ready)}",
           f"- **UNAVAILABLE (needs a model / runtime not bundled):** "
           f"{sum(1 for r in rows if r['availability'] == 'UNAVAILABLE')}",
           f"- **NOT_IMPLEMENTED (out of scope by design, e.g. detector evasion):** "
           f"{sum(1 for r in rows if r['availability'] == 'NOT_IMPLEMENTED')}", "",
           "## Capability classification", "",
           "| Method | Name | Family | Availability | " + " | ".join(CAPABILITY_FLAGS) + " | Classification |",
           "|---|---|---|---|" + "|".join(["---"] * len(CAPABILITY_FLAGS)) + "|---|"]
    for r in rows:
        caps = " | ".join("yes" if r["capabilities"][k] else "-" for k in CAPABILITY_FLAGS)
        out.append(f"| {r['method_id']} | {r['name']} | {r['fingerprint_family']} | {r['availability']} | {caps} | "
                   f"{', '.join(r['classification'])} |")
    out += ["", "## Unavailable / not implemented — honest reasons", ""]
    for r in rows:
        if not r["runnable"]:
            out.append(f"- **{r['method_id']} {r['name']}** ({r['availability']}): {r['reason_if_unavailable']}")
    out += ["", "## Taxonomy family coverage", ""]
    for fam, ids in matrix["families"].items():
        out.append(f"- **{fam}**: {', '.join(ids)}")
    out.append("")
    return "\n".join(out)


def main() -> int:
    matrix = build()
    (ROOT / "data" / "fingerprint_execution_matrix.json").write_text(
        json.dumps(matrix, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    (ROOT / "docs" / "UPGRADE_V6_IMPLEMENTATION_AUDIT.md").write_text(audit_markdown(matrix), encoding="utf-8")
    ready = sum(1 for r in matrix["methods"] if r["runnable"])
    print(f"Wrote data/fingerprint_execution_matrix.json and docs/UPGRADE_V6_IMPLEMENTATION_AUDIT.md: "
          f"{matrix['n_methods']} methods, {ready} runnable, {len(matrix['families'])} families")
    return 0


if __name__ == "__main__":
    sys.exit(main())
